language: ruby
notifications:
  email:
    - int-toolkit@schubergphilis.com
sudo: false
cache: bundler
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y bsdtar
  - gem install bundler -v '1.5.2'
rvm:
  - 2.0.0
script: rake
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/83f6eebe81bad15857f4
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
